use std::path::Path;
use axum::extract::State;
use axum::Json;
use axum::response::IntoResponse;
use serde::Deserialize;
use axum::http::StatusCode;
use serde_json::json;
use crate::AppState;
use crate::helpers::servers::install_server;
use crate::logs::logs;
use crate::structs::{server, blueprint, network, resources};
use crate::structs::server::{InstallStatus, ServerState};

#[derive(Deserialize)]
pub struct ServerCreationPayload {
    server_id: String,

    restart_policy: server::RestartPolicy,
    blueprint: blueprint::Blueprint,
    install_image_override: Option<String>,

    allocations: Option<Vec<network::Allocation>>,
    network_mode: network::NetworkMode,

    resources: resources::Resources,

    start_after_creation: bool,
    skip_install_script: bool,
}

/// # Server creation handler
///
/// The server creation handler accepts the following payload:
/// ```
/// server_id // ID of the server generated by the panel. Sent as a string for flexibility.
/// blueprint {
///     image_url // Docker image to use for this server's container.
///     install_script // A setup script to (optionally) run after creation.
///     start_command // The command used to start the server.
///     use_shell // Determines whether the container will use a shell
/// }
/// allocations {
///     port // The port used for the allocation.
///     protocol // The protocol (TCP/UDP) used for the allocation.
/// }
/// network_mode {
///     None // The server has no in/outbound internet connection.
///     Private // The server only has outbound internet connection.
///     Public // The server has inbound & outbound internet connection.
/// }
/// resources {
///     CPU // Max CPU available for the server, sent in millicores.
///     RAM // Max RAM available for the server, sent in MiB.
///     Swap // Max swap available for the server, sent in MiB.
///     Disk // Max disk space available for the server, sent in MiB.
/// }
/// start_after_creation // Determines whether the server is started after creation & installation.
/// skip_install_script // Determines whether the install script is run or not.
/// ```
///
/// ## Notes
///
/// - The Docker container name will always be `nodectl-server-{id}`, so there's no reason
/// to store the container name separately.
/// - Server directory will always be called `server-{id}`.

// Cleanup will run if anything in the handler fails halfway.
async fn server_cleanup(
    verbose: bool,
    server_id: &str,
    server_dir: &Path,
) {
    logs::verbose(verbose, &format!(
        "Starting cleanup for server [{}].",
        server_id
    ));
    
    // Delete server directory
    if let Err(e) = tokio::fs::remove_dir_all(server_dir).await {
        logs::warn(&format!(
            "Failed to delete server directory [{}]: {}",
            server_dir.display(),
            e,
        ))
    }

    logs::verbose(verbose, &format!(
        "Finished cleanup for server [{}].", server_id,
    ));
}

pub async fn create_server_handler(
    State(state): State<AppState>,
    Json(p): Json<ServerCreationPayload>,
) -> Result<impl IntoResponse, impl IntoResponse> {
    // State vars
    let db = &state.db;
    let cfg = &state.cfg;

    // Destructure payload
    let ServerCreationPayload {
        server_id,
        restart_policy,
        blueprint,
        install_image_override,
        allocations,
        network_mode,
        resources,
        start_after_creation,
        skip_install_script
    } = p;

    // Validate resources
    if resources.cpu < -1
    || resources.ram < -1
    || resources.swap < -1
    || resources.disk < -1 {
        return Err((
            StatusCode::UNPROCESSABLE_ENTITY,
            Json(json!({
                "error": "Resources cannot be lower than -1.",
            }))
        ).into_response());
    }

    // Init server directory
    let server_dir = cfg.paths.servers.join(format!("server-{}", server_id.clone()));

    // Start DB transaction
    let mut tx = match db.begin().await {
        Ok(tx) => tx,
        Err(e) => {
            logs::error(&format!(
                "Failed to start transaction for server [{}]: {}",
                &server_id, e,
            ));
            server_cleanup(cfg.verbose, &server_id, &server_dir).await;
            return Err((StatusCode::INTERNAL_SERVER_ERROR, Json(json!({
                "error": "Failed to start DB transaction.",
            }))).into_response());
        }
    };

    // Loop over each allocation and check whether its [port, protocol] combination is already
    // in use by another server.
    // Note: TCP and UDP ports don't collide - One server can have TCP 80, another can
    // have UDP 80, and they won't collide.
    if let Some(allocs) = &allocations {
        for alloc in allocs {
            logs::verbose(cfg.verbose, &format!(
                "Checking allocation [{}/{}] in database.", &alloc.port, &alloc.protocol.as_str()
            ));
            let exists: bool = match sqlx::query_scalar(
                // language=postgresql
                r#"
                SELECT EXISTS (
                    SELECT 1 FROM allocations
                    WHERE port = $1
                    AND protocol = $2
                )
                "#
            )
                .bind(alloc.port)
                .bind(alloc.protocol.as_str())
                .fetch_one(&mut *tx)
                .await {
                Ok(res) => res,
                Err(_) => {
                    server_cleanup(cfg.verbose, &server_id, &server_dir).await;
                    return Err((StatusCode::INTERNAL_SERVER_ERROR, Json(json!({
                        "error": "Internal Server Error.",
                    }))).into_response())
                }
            };

            if exists {
                return {
                    server_cleanup(cfg.verbose, &server_id, &server_dir).await;
                    Err((StatusCode::CONFLICT, Json(json!({
                        "error": "One or more of the allocations are already in use.",
                    }))).into_response())
                }
            }
        }
    }

    // Create server directory
    logs::verbose(cfg.verbose, &format!(
        "Creating server directory [{}].", server_dir.clone().display()
    ));
    if let Err(e) = tokio::fs::create_dir(&server_dir).await {
        if e.kind() == std::io::ErrorKind::AlreadyExists {
            return {
                Err((StatusCode::CONFLICT, Json(json!({
                    "error": &format!("The server directory [{}] already exists.", &server_dir.display())
                }))).into_response())
            }
        }

        logs::error(&format!(
            "Failed to create server directory [{}]: {}", &server_dir.display(), e
        ));

        server_cleanup(cfg.verbose, &server_id, &server_dir).await;
        return Err((StatusCode::INTERNAL_SERVER_ERROR, Json(json!({
            "error": "Failed to create server directory.",
        }))).into_response());
    }

    // --- Server data & quotas ---

    // TODO: Implement project quotas, apply size limit to the data directory created below.
    // Skipping for now to focus on more important stuff.
    // Create directory
    let data_dir = server_dir.join("data");
    if let Err(e) = tokio::fs::create_dir_all(&data_dir).await {
        logs::error(&format!(
            "Failed to create server data directory [{}]: {}",
            data_dir.display(), e,
        ));

        server_cleanup(cfg.verbose, &server_id, &server_dir).await;
        return Err((StatusCode::INTERNAL_SERVER_ERROR, Json(json!({
            "error": "Failed to create server data directory.",
        }))).into_response());
    }

    // Create blueprint struct
    let server_blueprint = blueprint::Blueprint {
        image_url: blueprint.image_url,
        install_script: blueprint.install_script,
        start_command: blueprint.start_command.into(),
        stop_command: blueprint.stop_command.into(),
        use_shell: blueprint.use_shell,
    };

    // --- Docker ---

    // Create server struct
    let server = server::Server {
        id: server_id.to_string(),
        container_id: None, // Added later

        // Default to installing state. It'll be changed
        // later in the install_server function.
        state: ServerState::Installing,
        // Default to pending, changed later in install_server function.
        install_status: InstallStatus::Pending,
        restart_policy,

        blueprint: server_blueprint,

        network_mode,
        allocations,

        resources,
    };

    // --- Store in database ---

    // 1. Store server
    if let Err(e) = sqlx::query(r#"
        INSERT INTO servers (id, state, install_status, restart_policy, network_mode)
        VALUES ($1, $2, $3, $4, $5)
    "#)
        .bind(&server.id)
        .bind(&server.state.as_str())
        .bind(&server.install_status.as_str())
        .bind(&server.restart_policy.as_str())
        .bind(&server.network_mode.as_str())
        .execute(&mut *tx)
        .await {
        logs::error(&format!(
            "Failed to insert server row for server [{}]: {}", &server.id, e
        ));

        server_cleanup(cfg.verbose, &server_id, &server_dir).await;
        return Err((StatusCode::INTERNAL_SERVER_ERROR, Json(json!({
            "error": "Failed to insert server row into the database.",
        }))).into_response())
    }

    // 2. Store blueprint
    if let Err(e) = sqlx::query(r#"
        INSERT INTO blueprints (server_id, image_url, install_script, start_command, stop_command, use_shell)
        VALUES ($1, $2, $3, $4, $5, $6)
    "#)
        .bind(&server.id)
        .bind(&server.blueprint.image_url)
        .bind(serde_json::to_value(&server.blueprint.install_script).unwrap_or_default())
        .bind(serde_json::to_value(&server.blueprint.start_command).unwrap_or_default())
        .bind(serde_json::to_value(&server.blueprint.stop_command).unwrap_or_default())
        .bind(&server.blueprint.use_shell)
        .execute(&mut *tx)
        .await {
        logs::error(&format!(
            "Failed to insert blueprint row for server [{}]: {}", &server.id, e)
        );

        server_cleanup(cfg.verbose, &server_id, &server_dir).await;
        return Err((StatusCode::INTERNAL_SERVER_ERROR, Json(json!({
            "error": "Failed to insert blueprint into the database.",
        }))).into_response());
    }

    // 3. Store server resources
    if let Err(e) = sqlx::query(r#"
        INSERT INTO server_resources (server_id, cpu, ram, swap, disk)
        VALUES ($1, $2, $3, $4, $5)
    "#)
        .bind(&server.id)
        .bind(&server.resources.cpu)
        .bind(&server.resources.ram)
        .bind(&server.resources.swap)
        .bind(&server.resources.disk)
        .execute(&mut *tx)
        .await {
        logs::error(&format!("Failed to insert server row for server [{}]: {}", &server.id, e));

        server_cleanup(cfg.verbose, &server_id, &server_dir).await;
        return Err((StatusCode::INTERNAL_SERVER_ERROR, Json(json!({
            "error": "Failed to insert server row.",
        }))).into_response());
    }

    // 4. Store server allocations if any are available
    if let Some(allocs) = &server.allocations {
        for alloc in allocs {
            if let Err(e) = sqlx::query(r#"
                INSERT INTO allocations (server_id, port, protocol)
                VALUES ($1, $2, $3)
            "#)
                .bind(&server.id)
                .bind(&alloc.port)
                .bind(&alloc.protocol.as_str())
                .execute(&mut *tx)
                .await {
                if let sqlx::Error::Database(db_err) = &e {
                    if db_err.is_unique_violation() {
                        return Err((
                            StatusCode::CONFLICT,
                            Json(json!({
                                "error": format!(
                                    "The allocation [{}/{}] is already taken.",
                                    &alloc.port, &alloc.protocol.as_str(),
                                )
                            }))
                        ).into_response());
                    }
                }

                logs::error(&format!(
                    "Failed to insert allocation row for server [{}]: {}",
                    &server.id, e,
                ));

                server_cleanup(cfg.verbose, &server_id, &server_dir).await;
                return Err((StatusCode::INTERNAL_SERVER_ERROR, Json(json!({
                    "error": "Failed to insert allocation row.",
                }))).into_response());
            }
        }
    }


    // Commit DB transaction
    if let Err(e) = tx.commit().await {
        logs::error(&format!("Failed to commit transaction for server [{}]: {}",
            &server_id, &e
        ));
        server_cleanup(cfg.verbose, &server_id, &server_dir).await;
        return Err((
            StatusCode::INTERNAL_SERVER_ERROR,
            Json(json!({
                "error": "Failed to commit database transaction."
            }))
        ).into_response());
    }

    logs::info(&format!(
        "Created server [{}].", server_id,
    ));

    // --- Install script & start ---
    // In an async thread
    let config = cfg.clone();
    tokio::spawn(async move {
        install_server(&config, state, server, &data_dir, &install_image_override, skip_install_script, start_after_creation)
            .await;
    });

    Ok(StatusCode::NO_CONTENT)
}